ALTER TABLE document_chunks
    ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'pdf',
    ADD COLUMN IF NOT EXISTS object_key TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS location JSONB NOT NULL DEFAULT '{}';
